language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 hello.c -o hello
  - ./hello
  - gcov hello.c

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/feature/disable-gcov-branches/codecov)
